<?php

/**
 * PluginAuthNetTransactionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginAuthNetTransactionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginAuthNetTransactionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginAuthNetTransaction');
    }
}