<?php

/**
 * PluginAuthNetTransactionErrorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginAuthNetTransactionErrorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginAuthNetTransactionErrorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginAuthNetTransactionError');
    }
}